export const REGISTER = '/api/register'
export const PROFILE_ROUTE = '/api/profile'
export const LOGIN = '/api/login'
export const UPLOAD_FILE = '/api/upload'
export const VERIFY_EMAIL = '/api/send/email_verification'
export const VERIFY_PHONE = '/api/send/sms'
export const ADDRESS_PATH = '/api/profile/address'
