import type { Metadata } from "next";
import "./globals.css";
import { NavProvider } from "@/context/navContext";
import { NavBar } from "@/components/navs/NavBar";
import { Nabvar_Movil } from "@/components/navs/Nabvar_Movil";
import { siligury } from "@/utils/fonts";
import { NavBarScroll } from "@/components/navs/NavBarScroll";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${siligury.className} antialiased h-auto min-h-screen bg-darkMode flex flex-col justify-between`}>
        <NavProvider>
          <header className="w-full overflow-hidden absolute z-20">
            <Nabvar_Movil />
            <NavBarScroll />
            <NavBar />
          </header>
          <main className="w-full overflow-hidden grow">{children}</main>
          <Footer />
        </NavProvider>
      </body>
    </html>
  );
}
