import type { Metadata } from "next";
import "./globals.css";
import { NavProvider } from "@/context/navContext";
import { siligury } from "@/utils/fonts";
import { Providers } from "./Providers";
import { ProfileProvider } from "@/context/profileContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${siligury.className} antialiased h-auto min-h-screen bg-darkMode flex flex-col justify-between`}
      >
        <Providers>
          <ProfileProvider>
            <NavProvider>
              <main className="w-full overflow-hidden grow">{children}</main>
            </NavProvider>
          </ProfileProvider>
        </Providers>
      </body>
    </html>
  );
}
