import { siligury } from '@/utils/fonts'
import type { Metadata } from 'next'
import { Toaster } from 'react-hot-toast'
import { Providers } from './Providers'
import './globals.css'

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html lang="en">
         <body
            className={`${siligury.className} antialiased h-auto min-h-screen bg-darkMode flex flex-col justify-between`}
         >
            <Providers>
               <main className="w-full overflow-hidden grow">
                  <Toaster />
                  {children}
               </main>
            </Providers>
         </body>
      </html>
   )
}
